project_id = "boomcddxjyuyytmlpvtw"

[functions.ingest-activity]
verify_jwt = false

[functions.generate-xai-explanation]
verify_jwt = true
[functions.get-threat-prediction]
enabled = true
verify_jwt = true
import_map = "./functions/get-threat-prediction/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-threat-prediction/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-threat-prediction/*.html" ]
